### ISSUE TITLE
Substitutions may not be used with dynamic templating

### ISSUE THREAD

**Issue by Hamdan85** [sendgrid/sendgrid-ruby#299] opened 2018-07-24 03:01 UTC
#### Issue Summary

I got 400 error trying to send a transactional template:

```ruby
class UserMailer < ApplicationMailer
  require 'sendgrid-ruby'
  include SendGrid

  def welcome(user)
    mail = Mail.new
    mail.from = Email.new(email: user.email)
    personalization = Personalization.new
    personalization.add_to(Email.new(email: user.email, name: user.name))
    personalization.add_substitution(Substitution.new(key: '-name-', value: user.name))
    mail.add_personalization(personalization)

    mail.template_id = '<my template id>'

    sg = SendGrid::API.new(api_key: ENV['SENDGRID_API_KEY'])
    response = sg.client.mail._('send').post(request_body: mail.to_json)
    puts response.status_code
    puts response.body
    puts response.headers
  end
end
```

#### Response

```ruby
=> #<SendGrid::Response:0x00007fbe6650bb40 @status_code="400", @body="{\"errors\":[{\"message\":\"Substitutions may not be used with dynamic templating\",\"field\":\"personalizations.0.substitutions\",\"help\":\"http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.personalizations.substitutions\"}]}", @headers={"server"=>["nginx"], "date"=>["Tue, 24 Jul 2018 02:58:15 GMT"], "content-type"=>["application/json"], "content-length"=>["238"], "connection"=>["close"], "access-control-allow-origin"=>["https://sendgrid.api-docs.io"], "access-control-allow-methods"=>["POST"], "access-control-allow-headers"=>["Authorization, Content-Type, On-behalf-of, x-sg-elas-acl"], "access-control-max-age"=>["600"], "x-no-cors-reason"=>["https://sendgrid.com/docs/Classroom/Basics/API/cors.html"]}>
```

#### Technical details:

* sendgrid-ruby Version: master
* Ruby Version: 2.5.1p57

**Comment by thinkingserious** [comment] 2018-07-24 03:18
Hello @Hamdan85,

I think there may be a bug where you need to add the following:

`mail.add_content(Content.new(type: 'text/html', value: ''))` right before `mail.template_id = '<my template id>'`. 

Could you please try that?

Thanks!

With Best Regards,

Elmer

**Comment by thinkingserious** [comment] 2018-07-24 03:31
Can you please share what the HTML looks like? Thanks!

**Comment by Hamdan85** [comment] 2018-07-24 03:38
There's no HTML... that's the point of using the template_id which is the id of a template that has the HTML in sendgrid platform.
Am I wrong?

**Comment by thinkingserious** [comment] 2018-07-24 03:49
Yes, I’m referring to the HTML in the SendGrid platform. I’m trying to reproduce the error. Thanks!

**Comment by Hamdan85** [comment] 2018-07-24 04:16
Ok.

I have chosed the variable name in several formats: {{name}}, -name-, %name%
nothing works
Here's the code:
```html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html data-editor-version="2" class="sg-campaigns" xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1" /><!--[if !mso]><!-->
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" /><!--<![endif]-->
    <!--[if (gte mso 9)|(IE)]>
    <xml>
    <o:OfficeDocumentSettings>
    <o:AllowPNG/>
    <o:PixelsPerInch>96</o:PixelsPerInch>
    </o:OfficeDocumentSettings>
    </xml>
    <![endif]-->
    <!--[if (gte mso 9)|(IE)]>
    <style type="text/css">
      body {width: 600px;margin: 0 auto;}
      table {border-collapse: collapse;}
      table, td {mso-table-lspace: 0pt;mso-table-rspace: 0pt;}
      img {-ms-interpolation-mode: bicubic;}
    </style>
    <![endif]-->

    <style type="text/css">
      body, p, div {
        font-family: arial;
        font-size: 14px;
      }
      body {
        color: #000000;
      }
      body a {
        color: #1188E6;
        text-decoration: none;
      }
      p { margin: 0; padding: 0; }
      table.wrapper {
        width:100% !important;
        table-layout: fixed;
        -webkit-font-smoothing: antialiased;
        -webkit-text-size-adjust: 100%;
        -moz-text-size-adjust: 100%;
        -ms-text-size-adjust: 100%;
      }
      img.max-width {
        max-width: 100% !important;
      }
      .column.of-2 {
        width: 50%;
      }
      .column.of-3 {
        width: 33.333%;
      }
      .column.of-4 {
        width: 25%;
      }
      @media screen and (max-width:480px) {
        .preheader .rightColumnContent,
        .footer .rightColumnContent {
            text-align: left !important;
        }
        .preheader .rightColumnContent div,
        .preheader .rightColumnContent span,
        .footer .rightColumnContent div,
        .footer .rightColumnContent span {
          text-align: left !important;
        }
        .preheader .rightColumnContent,
        .preheader .leftColumnContent {
          font-size: 80% !important;
          padding: 5px 0;
        }
        table.wrapper-mobile {
          width: 100% !important;
          table-layout: fixed;
        }
        img.max-width {
          height: auto !important;
          max-width: 480px !important;
        }
        a.bulletproof-button {
          display: block !important;
          width: auto !important;
          font-size: 80%;
          padding-left: 0 !important;
          padding-right: 0 !important;
        }
        .columns {
          width: 100% !important;
        }
        .column {
          display: block !important;
          width: 100% !important;
          padding-left: 0 !important;
          padding-right: 0 !important;
          margin-left: 0 !important;
          margin-right: 0 !important;
        }
      }
    </style>
    <!--user entered Head Start-->
    
     <!--End Head user entered-->
  </head>
  <body>
    <center class="wrapper" data-link-color="#1188E6" data-body-style="font-size: 14px; font-family: arial; color: #000000; background-color: #ffffff;">
      <div class="webkit">
        <table cellpadding="0" cellspacing="0" border="0" width="100%" class="wrapper" bgcolor="#ffffff">
          <tr>
            <td valign="top" bgcolor="#ffffff" width="100%">
              <table width="100%" role="content-container" class="outer" align="center" cellpadding="0" cellspacing="0" border="0">
                <tr>
                  <td width="100%">
                    <table width="100%" cellpadding="0" cellspacing="0" border="0">
                      <tr>
                        <td>
                          <!--[if mso]>
                          <center>
                          <table><tr><td width="600">
                          <![endif]-->
                          <table width="100%" cellpadding="0" cellspacing="0" border="0" style="width: 100%; max-width:600px;" align="center">
                            <tr>
                              <td role="modules-container" style="padding: 0px 0px 0px 0px; color: #000000; text-align: left;" bgcolor="#ffffff" width="100%" align="left">
                                
    <table class="module preheader preheader-hide" role="module" data-type="preheader" border="0" cellpadding="0" cellspacing="0" width="100%"
           style="display: none !important; mso-hide: all; visibility: hidden; opacity: 0; color: transparent; height: 0; width: 0;">
      <tr>
        <td role="module-content">
          <p>Agora falta pouco... jajá te ligamos.</p>
        </td>
      </tr>
    </table>
  
    <table class="wrapper" role="module" data-type="image" border="0" cellpadding="0" cellspacing="0" width="100%" style="table-layout: fixed;">
      <tr>
        <td style="font-size:6px;line-height:10px;padding:0px 0px 0px 0px;" valign="top" align="center">
          <a href="https://cancelarammeuvoo.com.br"><img class="max-width" border="0" style="display:block;color:#000000;text-decoration:none;font-family:Helvetica, arial, sans-serif;font-size:16px;max-width:100% !important;width:100%;height:auto !important;" src="https://marketing-image-production.s3.amazonaws.com/uploads/5db65a3554ff036853826cc0c53a8c67d981a2ed964ee2f2615f9644566b7a5e34d40a3e436152030e227178c7b4d63afcc4a3539651d30344dd2e03b278a036.png" alt="logo" width="600"></a>
        </td>
      </tr>
    </table>
  
    <table class="module" role="module" data-type="text" border="0" cellpadding="0" cellspacing="0" width="100%" style="table-layout: fixed;">
      <tr>
        <td style="background-color:#ffffff;padding:18px 0px 18px 0px;line-height:22px;text-align:inherit;"
            height="100%"
            valign="top"
            bgcolor="#ffffff">
            <h1 style="text-align: center;">Muito obrigado por sua confiança.&nbsp;</h1>

<div>Olá -name-,</div>

<div>Muito obrigado por sua confiança. Em breve ligaremos para requisitar alguns documentos, uma procuração e mais dados sobre o ocorrido. Isso garante que nosso time jurídico faça tudo certinho pra gente resolver isso o mais rápido possível ok?</div>

<div>&nbsp;</div>

<div>Um grande abraço e até daqui a pouquinho.</div>
        </td>
      </tr>
    </table>
  <div data-role="module-unsubscribe" class="module unsubscribe-css__unsubscribe___2CDlR" role="module" data-type="unsubscribe" style="color:#444444;font-size:12px;line-height:20px;padding:16px 16px 16px 16px;text-align:center"><div class="Unsubscribe--addressLine"><p class="Unsubscribe--senderName" style="font-family:Arial,Helvetica, sans-serif;font-size:12px;line-height:20px">[Sender_Name]</p><p style="font-family:Arial,Helvetica, sans-serif;font-size:12px;line-height:20px"><span class="Unsubscribe--senderAddress">[Sender_Address]</span>, <span class="Unsubscribe--senderCity">[Sender_City]</span>, <span class="Unsubscribe--senderState">[Sender_State]</span> <span class="Unsubscribe--senderZip">[Sender_Zip]</span> </p></div><p style="font-family:Arial,Helvetica, sans-serif;font-size:12px;line-height:20px"><a class="Unsubscribe--unsubscribeLink" href="<%asm_group_unsubscribe_raw_url%>">Unsubscribe</a> - <a class="Unsubscribe--unsubscribePreferences" href="<%asm_preferences_raw_url%>">Unsubscribe Preferences</a></p></div>
                              </td>
                            </tr>
                          </table>
                          <!--[if mso]>
                          </td></tr></table>
                          </center>
                          <![endif]-->
                        </td>
                      </tr>
                    </table>
                  </td>
                </tr>
              </table>
            </td>
          </tr>
        </table>
      </div>
    </center>
  </body>
</html>
```

**Comment by Hamdan85** [comment] 2018-07-24 04:17
ps, my footer also doesnt work even if I have edited my account info. I dont have write power over footer params.

**Comment by thinkingserious** [comment] 2018-07-24 20:43
@Hamdan85,

Thanks for providing the HTML. 

Does the -name- placeholder stay as -name- or is it blank in the final email?

Also, have you tried running [this example](https://github.com/sendgrid/sendgrid-ruby/blob/master/USE_CASES.md#transactional-templates)?

With Best Regards,

Elmer

**Comment by Hamdan85** [comment] 2018-07-26 00:43
@thinkingserious but this example doesn't work anyway... the email arrives without the dynamic content... how can I use it?!

**Comment by thinkingserious** [comment] 2018-07-26 02:00
@Hamdan85,

Please try

```ruby
class UserMailer < ApplicationMailer
  require 'sendgrid-ruby'
  include SendGrid

  def welcome(user)
    data = {
      personalizations: [
        {
          to: [
            {
              email: user.email
            }
          ],
          dynamic_template_data: {
               name: user.name
          },
          subject: "NOT"
        }
      ],
      from: {
        email: "---@---.---.--"
      },
      template_id: "my api id"
    }
    response = SendGrid::API.new(api_key: ENV['SENDGRID_API_KEY']).client.mail._('send').post(request_body: data)
    p response
  end
end
```

And in the HTML use `{{name}}`

**Comment by PhucQuoine** [comment] 2018-07-26 06:56
@thinkingserious I got the same problem. 
There are some reasons so I'm using the old version `sendgrid-ruby-4.0.8`.
My template 
```
<div><div><p>
  Dear Support,
</p>
<p>
  A new user has just registered.  Details below:
  </p><ul>
    <li>Email: {{email}}</li>
    <li>Location: {{country_name}} ({{country_code}})</li>
    <li>ID: {{user_id}}</li>
  </ul>
<p></p>
<p>
  Regards
</p>
<strong>This one sent by sendgrid template.</strong></div></div>
```

My ruby code: 
```
mail = Mail.new
    @user = User.find(user_id)
    mail.subject = 'New registration'

    personalization = Personalization.new
    personalization.to = Email.new(email: 'support@mailinator.com')
    personalization.substitutions = Substitution.new(key: 'email', value: @user.email)
    personalization.substitutions = Substitution.new(key: 'country_name', value: @user.country_name)
    personalization.substitutions = Substitution.new(key: 'country_code', value: @user.country)
    personalization.substitutions = Substitution.new(key: 'user_id', value: @user.id.to_s)
    mail.personalizations = personalization

    mail.template_id = template_id_for('notify_new_user')
    mail.categories = Category.new(name: 'notify_new_user')
    mail.from = Email.new(email: Setting.support_email, name: 'Quoine Support')
    sg = SendGrid::API.new(api_key: SENDGRID_API_KEY)
    response = sg.client.mail._('send').post(request_body: mail.to_json)
```

Is there any way to make it work?

**Comment by PhucQuoine** [comment] 2018-07-26 06:57
@thinkingserious I got the same problem. 
There are some reasons so I'm using the old version `sendgrid-ruby-4.0.8`.
My template 
```
<div><div><p>
  Dear Support,
</p>
<p>
  A new user has just registered.  Details below:
  </p><ul>
    <li>Email: {{email}}</li>
    <li>Location: {{country_name}} ({{country_code}})</li>
    <li>ID: {{user_id}}</li>
  </ul>
<p></p>
<p>
  Regards
</p>
<strong>This one sent by sendgrid template.</strong></div></div>
```

My ruby code: 
```
mail = Mail.new
    @user = User.find(user_id)
    mail.subject = 'New registration'

    personalization = Personalization.new
    personalization.to = Email.new(email: 'support@mailinator.com')
    personalization.substitutions = Substitution.new(key: 'email', value: @user.email)
    personalization.substitutions = Substitution.new(key: 'country_name', value: @user.country_name)
    personalization.substitutions = Substitution.new(key: 'country_code', value: @user.country)
    personalization.substitutions = Substitution.new(key: 'user_id', value: @user.id.to_s)
    mail.personalizations = personalization

    mail.template_id = template_id_for('notify_new_user')
    mail.categories = Category.new(name: 'notify_new_user')
    mail.from = Email.new(email: Setting.support_email, name: 'Support')
    sg = SendGrid::API.new(api_key: SENDGRID_API_KEY)
    response = sg.client.mail._('send').post(request_body: mail.to_json)
```

Is there any way to make it work?

**Comment by Hamdan85** [comment] 2018-07-26 13:16
is there a rest doc? this lib seems way not ready for production... 
no demands here lol... it's just a observation.

**Comment by PhucQuoine** [comment] 2018-07-26 14:10
@Hamdan85 
There is a pull request waiting for review https://github.com/sendgrid/sendgrid-ruby/pull/300

**Comment by thinkingserious** [comment] 2018-07-26 20:30
Hello everyone!

Please see [this issue](https://github.com/sendgrid/sendgrid-ruby/issues/301) and PR #300 for progress and current work around.

Thanks for your assistance and patience!

With Best Regards,

Elmer

**Comment by thinkingserious** [comment] 2018-07-26 20:46
@Hamdan85,

Code similar to the following should work for v4.0.8:
```ruby
data = JSON.parse('{
  "categories": [
    "notify_new_user"
  ],
  "from": {
    "email": "'+Setting.support_email+'",
    "name": "Support"
  },
  "personalizations": [
    {
      "dynamic_template_data": {
        "email": "'+@user.email+'",
        "country_name": "'+@user.country_name+'",
        "country_code": "'+@user.country+'",
        "user_id": "'+@user.id.to_s+'"
      },
      "to": [
        {
          "email": "support@mailinator.com"
        }
      ]
    }
  ],
  "subject": "New registration",
  "template_id": "'+template_id_for('notify_new_user')+'"
}')
response = sg.client.mail._("send").post(request_body: data)
puts response.status_code
puts response.body
puts response.headers
```

**Comment by thinkingserious** [comment] 2018-07-27 00:42
It's [string interpolation](https://www.digitalocean.com/community/tutorials/how-to-work-with-strings-in-ruby#using-string-interpolation).

**Comment by Hamdan85** [comment] 2018-07-27 01:07
Lol...
Missed the ' in the beginning

Em qui, 26 de jul de 2018 21:43, Elmer Thomas <notifications@github.com>
escreveu:

**Comment by PhucQuoine** [comment] 2018-07-27 17:43
so much thank to @thinkingserious
It's work for me.

**Comment by PhucQuoine** [comment] 2018-07-27 19:16
@thinkingserious 
The email successfully sent. But there is another problem, the email subject doesn't show up while correct email content.

**Comment by Hamdan85** [comment] 2018-07-28 00:37
when i put {{name}} in template, it just says to me that the template is invalid on sendgrid UI... that's new.

**Comment by Hamdan85** [comment] 2018-07-28 01:52
how about the sender_name data for transactional templates? is it applies to this hash too?
bacause nothing in UI seems to be configuring these particular fields

**Comment by PhucQuoine** [comment] 2018-07-28 04:33
@Hamdan85 does the email subject shown up in your email?

**Comment by krzkrzkrz** [comment] 2018-07-28 15:35
Same here. Subject doesnt seem to work here!

**Comment by Hamdan85** [comment] 2018-07-28 18:00
I do can change de subject but by setting it with handlebar variables in
template... Not by using the subject key.

Try to put it in template like {{subject}} and set it together with your
other variables.

Lol... This doc/sdk seems very messy isn't it?



Em sáb, 28 de jul de 2018 12:35, Christian Fazzini <notifications@github.com>
escreveu:

**Comment by krzkrzkrz** [comment] 2018-07-28 23:13
@Hamdan85 Great! Thanks. That works

**Comment by pdkproitf** [comment] 2018-07-29 14:16
@Hamdan85 @krzkrzkrz It does not work with me.
My code:
```
def notify_new_user_v2(user_id)
    @user = User.find(user_id)
    data = JSON.parse('{
      "categories": [
        "notify_new_user"
      ],
      "from": {
        "email": "'+Setting.support_email+'",
        "name": "Support"
      },
      "personalizations": [
        {
          "dynamic_template_data": {
          },
          "to": [
            {
              "email": "'+@user.email+'"
            }
          ]
        }
      ],
      "subject": "New registration",
      "template_id": "'+template_id_for('notify_new_user')+'"
    }')

    sg = SendGrid::API.new(api_key: SENDGRID_API_KEY)
    response = sg.client.mail._("send").post(request_body: data)
    p '***************'
    p response
  end
```
My template: 
<img width="1316" alt="screen shot 2018-07-29 at 9 07 01 pm" src="https://user-images.githubusercontent.com/12691828/43367262-8403705c-9374-11e8-84da-657499f28d77.png">

**Comment by Hamdan85** [comment] 2018-07-29 14:30
I think u didn't understood: you should declare the {{subject}} in the
dynamic fields array...

Em dom, 29 de jul de 2018 11:16, Ryan Pham <notifications@github.com>
escreveu:

**Comment by pdkproitf** [comment] 2018-07-29 14:53
Oh, my bad.
Many thank @Hamdan85

**Comment by NavinGelot** [comment] 2018-07-30 08:48
Hey @Hamdan85  i am facing same problem with subject
my template is as following:

[<html>
<head>
	<title></title>
</head>
<body>
Hello {{name}},
<br /><br/>
I'm glad you are trying out the template feature!
<br /><br/>
<br /><br/>
I hope you are having a great day in {{city}} :)
<br /><br/>
</body>
</html>

and my i have json : 

{
  "from": {
    "email": "${from.getEmail}",
    "name": "${from.getName}"
  },
  "personalizations": [
    {
      "dynamic_template_data": {
        "name": "navin",
        "city": "AMD"
      },
      "to": [
        {
          "email": "${to.getEmail}"
        }
      ]
    }
  ],
  "subject": "$subject",
  "template_id": "myid"
}

I am getting the mail as i want but subject is empty.
Plz help me 
Many thanks..

**Comment by krzkrzkrz** [comment] 2018-07-30 09:31
@NavinGelot You need to include `subject` in `dynamic_template_data`:

```
"dynamic_template_data": {
  "subject": "Lorem ipsum",
  "name": "navin",
  "city": "AMD"
},
```

**Comment by NavinGelot** [comment] 2018-07-30 09:37
yes that i did but i forgot to to replace subject in ui Thanks @krzkrzkrz  :)

![email](https://user-images.githubusercontent.com/23419606/43389827-4d0d31be-940a-11e8-93d6-d26e5262da61.png)

**Comment by thinkingserious** [comment] 2018-07-30 23:18
Hello Everyone,

Have you tried including the subject key in the Personalization object? 

For example:

```ruby
def notify_new_user_v2(user_id)
    @user = User.find(user_id)
    data = JSON.parse('{
      "categories": [
        "notify_new_user"
      ],
      "from": {
        "email": "'+Setting.support_email+'",
        "name": "Support"
      },
      "personalizations": [
        {
          "dynamic_template_data": {
          },
          "to": [
            {
              "email": "'+@user.email+'"
            }
          ]
        },
        "subject": "New registration",
      ],
      "template_id": "'+template_id_for('notify_new_user')+'"
    }')

    sg = SendGrid::API.new(api_key: SENDGRID_API_KEY)
    response = sg.client.mail._("send").post(request_body: data)
    p '***************'
    p response
  end
```

That said, including a subject outside of the Personaliztion object should act as a global override. I'll leave this issue open and on our backlog for further investigation.

With Best Regards,

Elmer

**Comment by pdkproitf** [comment] 2018-07-31 03:07
@thinkingserious thing
I did. But it didn't work with the dynamic template.

**Comment by thinkingserious** [comment] 2018-07-31 03:16
Thanks for the confirmation @pdkproitf.

**Comment by achempion** [comment] 2018-08-09 16:43
I think that is some sort of trolling. We have the docs with explicit arguments such as `template_id` and `substitutions` but that is not working as expected. 

https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html 

To make things work we should spend hours to finally get the answer — we need to use `{{ val }}` inside the template and
```json
"personalizations": {
    "dynamic_template_data": {
        "val": "some text"
    }
}
```
as the argument for an api. Which is not mentioning anywhere.

The documentation quality is complete joke.

**Comment by Hamdan85** [comment] 2018-08-09 17:29
I wouldn't say that but is quite annoying.

Em qui, 9 de ago de 2018 13:43, Boris Kuznetsov <notifications@github.com>
escreveu:

**Comment by thinkingserious** [comment] 2018-08-14 00:16
Hello @achempion,

Thanks for your feedback and taking the time to post a solution. 

An update is coming shortly. 

Please check out [this issue](https://github.com/sendgrid/sendgrid-ruby/issues/301) for details. Specifically, [this PR](https://github.com/sendgrid/sendgrid-ruby/pull/300) is just about ready to go live.

With Best Regards,

Elmer

**Comment by 24601** [comment] 2018-08-20 22:54
Setting dynamic_template_data instead of substitutions *NEEDS* to be documented VERY VERY clearly. It is NOT documented ANYWHERE but here, and it just silently FAILS. 

This cost us an entire afternoon of frustration.

The docs are contradictory and don't match reality!

**Comment by thinkingserious** [comment] 2018-08-21 01:11
You are correct @24601.

We have released support for PHP and Python and are now working on C#. Next is Java, then Node.js, then Go and then this SDK. 

My apologies for the delay. 

Everyone,

Please follow [this issue](https://github.com/sendgrid/sendgrid-ruby/issues/301) for progress.

**Comment by thinkingserious** [comment] 2018-08-21 20:51
I'm closing out this issue to help consolidate things. Please check out [this issue](https://github.com/sendgrid/sendgrid-ruby/issues/301) for details.

**Closed by thinkingserious** 2018-08-21 20:51 UTC
Labels: difficulty: unknown or n/a, status: help wanted, type: bug

**Comment by kwent** [comment] 2018-08-24 23:56
Posting my solution since i spent as well wayyyyy too much time to make this work. Documentation needs to be revisited for sure.

## Sendgrid Template GUI side:

<img width="921" alt="screen shot 2018-08-24 at 4 50 23 pm" src="https://user-images.githubusercontent.com/879780/44612507-ea845a00-a7bd-11e8-8855-31601c1bfb1c.png">

Then modify the subject object to the following code:

```html
<span style="display:none">{{ subject }}</span>
```

Note: ```{{{ body }}} vs {{ body }}``` is to handle html

## Sendgrid Ruby SDK API side:

```ruby
    data = {
      from: {
        email: "no-reply@acme.com",
        name: "Acme"
      },
      personalizations: [
        dynamic_template_data: {
          subject: "Hello world",
          body: "<strong>Body is strong<strong>"
        },
        to: [{
          email: "user@example.com",
          name: "John Doe"
        }]
      ],
      template_id: "my_template_id"
    }

    begin
      sg = SendGrid::API.new(api_key: ENV['SENDGRID_API_KEY'])
      response = sg.client.mail._("send").post(request_body: data)
    rescue Exception => e
      Rollbar.error(e)
    end
```

**Comment by andela-venogwe** [comment] 2018-09-03 16:33
Wondering if the PR is merged.
The helper methods helps keep things clean and easy.
I currently just avoid using the `add_substitution method`.

I got mine working by adding the key `dynamic_template_data` to the personalizations Array as stated above.

If you have multiple personalizations, you can reference them by index or do a loop on the `mail.personalizations` Array. Where `mail` is an instance of `Mail`.

eg. `mail.personalizations[0]['dynamic_template_data'] = data`
where `data` is a Hash which contains your template substitutions.
eg. `{ title: 'lorem ipsum', description: 'dolor sit amet' }`

The Interpolation should look like this `{{title}}` in your templates.

**Comment by thinkingserious** [comment] 2018-09-05 23:51
Hello @andela-venogwe,

The PR is merged, but the gem has not been updated yet. If you subscribe to our [release notifications](https://dx.sendgrid.com/newsletter/ruby) you will receive an email once it's live.

Thanks!

With Best Regards,

Elmer

**Comment by Hamdan85** [comment] 2018-09-06 01:52
That's starting to become dramatic lol

Em qua, 5 de set de 2018 20:51, Elmer Thomas <notifications@github.com>
escreveu:

**Comment by HokhyTann** [comment] 2018-09-17 02:55
How about the URL of a button? How can we dynamically set it?

**Comment by kylearoberts** [comment] 2018-09-17 13:47
Hey @HokhyTann 

You should be able to set a URL dynamically using something like this:

```
<a href='{{{url}}}'> Link </a>
```

You likely want to use the triple bracket so that handlebars does not encode any of the link. Just make sure the link you are substituting is correctly URL encoded and you should be good.

**Comment by HokhyTann** [comment] 2018-09-18 02:55
@kylearoberts thank you somuch, got it working now

**Comment by joncursi** [comment] 2018-10-12 14:23
Okay... so this wasn't well-documented, but I wanted to share my finding.

You can supply `dynamic_template_data` both outside and inside of `personalizations`. If you have a bunch of dynamic template data that is shared among all recipients, but then want to personalize something like a `firstName` field for each user, you can do this:

```js
const dynamicTemplateData = { ... };

sendgrid.send(
  {
    dynamic_template_data: dynamicTemplateData,
    from: 'xx@xx.xx',
    personalizations: [
      {
        dynamic_template_data: {
          firstName: 'Jon',
        },
        to: 'xx@xx.xx',
      },
      {
        dynamic_template_data: {
          firstName: 'Jane',
        },
        to: 'xx@xx.xx',
      },
    ],
    templateId: 'xxx',
  });
```

**Comment by kylearoberts** [comment] 2018-10-12 15:30
@joncursi 

Thanks for the great testing. I tried to replicate what you did but did not have any luck. Could you take a look and let me know what I am doing differently:

```
curl -X POST \
  https://api.sendgrid.com/v3/mail/send \
  -H 'Authorization: Bearer API Key' \
  -H 'Content-Type: application/json' \
  -H 'cache-control: no-cache' \
  -d '{
	"dynamic_template_data": {
		"subject": "Hello World!"
	},
	"personalizations": [{
		"to": [{
			"email": "xx@xx.xx"
		}],
		"dynamic_template_data": {
			"first_name": "Kyle"
		}
	}],
	"from": {
		"email": "xx@xx.xx"
	},
	"reply_to": {
		"email": "xx@xx.xx"
	},
	"template_id": "xxx"
}'
```

The dynamic data in the personalization works, but not the dynamic data outside the personalization. It looks like I am doing it the same way as you, but since it is not working I must be missing something.

**Comment by joncursi** [comment] 2018-10-12 16:52
@kylearoberts that looks good to me. Not sure why it's not working. I defer to the SendGrid team on this one.

FWIW, I am firing my requests using the [@sendgrid/mail](https://www.npmjs.com/package/@sendgrid/mail) library.

**Comment by kylearoberts** [comment] 2018-10-12 17:17
@Ume1931 

Looks like thing just got [updated](https://github.com/sendgrid/sendgrid-ruby/releases/tag/v5.3.0).  Looks like the only thing left is for the creation of some [examples](https://github.com/sendgrid/sendgrid-ruby/issues/342) on how to use it.

@joncursi 

I'll see what I can do to replicate the issue and get it to our engineers.

**Comment by fsa-development** [comment] 2019-05-26 21:22
ya'll really need to stop changing templates to "legacy" 
you've introduced backwards-incompatible "upgrades" to templating multiple times in the last couple years
this is terrible product design 

you should either make forward-compatible types or make all backwards-incompatible changes in the API and SDK, and keep previous versions of the API running. So if I'm using v4 of the API and v4 of the SDK it will never break and never lose the ability to make compatible templates in the dashboard

ugh why do we have to tell you this

**Comment by thinkingserious** [comment] 2019-05-28 17:27
Hello @fsa-development,

I would love to help resolve your issue. Is it your current goal to use our "legacy" templating with the most up to date version of this SDK? If so, [this example](https://github.com/sendgrid/sendgrid-ruby/blob/master/USE_CASES.md#legacy-templates) should work. 

With Best Regards,

Elmer
